spring:
  profiles:
    active: ${env}
  jackson:
    time-zone: GMT+8

server:
  servlet:
    context-path: /api

mybatis-plus:
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  type-aliases-package: com.where.soul.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
