server:
  port: 9555

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/where_soul?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8

logging:
  level:
    com:
      where:
        soul: INFO
